name: Run repo-add for x86_64 packages

on:
  push:
    paths:
      - 'x86_64/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

    - name: Run repo-add
      run: |
        repo-add -n -R -q x86_64/tunalad.db.tar.gz x86_64/*.pkg.tar.zst
        rm -f x86_64/tunalad.db x86_64/tunalad.files
        mv x86_64/tunalad.db.tar.gz x86_64/tunalad.db
        mv x86_64/tunalad.files.tar.gz x86_64/tunalad.files

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add x86_64/tunalad.db x86_64/tunalad.files
        git commit -m "Update repository database"
        git push
